apiVersion: v1
kind: ConfigMap
metadata:
  name: pv-file-gg
data:
  dummy.txt: |
    This is a dummy file.
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container-welltech
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: pv-file
      items:
      - key: dummy.txt
        path: dummy.txt
